In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [9]:
data = pd.read_csv('data\data.csv')
data.head()

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\Administrator\AppData\Local\Temp\ipykernel_1284\1532519782.py:1: SyntaxWarning: invalid escape sequence '\d'
  data = pd.read_csv('data\data.csv')

,Unnamed: 0,party_rk,region,offenceshortstatement,engine_type,engine_power,body_type,auto_mark,auto_year,auto_model,...,car_price,gender_cd_M-1_F-0,age,marital_status_cd,children_cnt,education_level_cd,person_monthly_income_amt,day_of_week,public_holiday_1-f_0-t,offencedatetime
0,0,6.220256e+08,Москва,Движение по обочине,1.8,152.0,Универсал (5 дв.),SKODA,2011.0,OCTAVIA,...,712.0,1,23.0,UNM,0.0,UGR,80.0,Среда,1,2024-05-15 09:52:48
1,1,6.961338e+08,Воронежская область,Превышение скорости на 40-60 км/ч,1.6,73.0,Седан (4 дв.),LADA (ВАЗ),2011.0,2107,...,162.0,1,19.0,NaN,0.0,NaN,45.0,Понедельник,1,2024-05-13 17:54:58
2,2,1.057242e+09,Севастополь,Превышение скорости на 20-40 км/ч,2.5,145.0,Микроавтобус (5 дв.),HYUNDAI,2018.0,GRAND STAREX,...,2601.0,1,43.0,NaN,0.0,NaN,500.0,Пятница,0,2024-05-10 00:29:11
3,3,3.006247e+08,Республика Тыва,Превышение скорости на 20-40 км/ч,2.0,150.0,Седан (4 дв.),MITSUBISHI,2007.0,LANCER,...,410.0,1,27.0,UNM,0.0,SCH,35.0,Четверг,1,2024-05-02 21:44:46
4,4,7.024843e+08,Воронежская область,Превышение скорости на 20-40 км/ч,2.3,155.0,Универсал (5 дв.),FORD,2004.0,ESCAPE,...,617.0,0,42.0,MAR,0.0,GRD,50.0,Воскресенье,0,2024-04-28 16:25:51

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97307 entries, 0 to 97306
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Unnamed: 0                 97307 non-null  int64
 1   party_rk                   97306 non-null  float64
 2   region                     97306 non-null  object
 3   offenceshortstatement      97306 non-null  object
 4   engine_type                97306 non-null  float64
 5   engine_power               97306 non-null  float64
 6   body_type                  97306 non-null  object
 7   auto_mark                  97306 non-null  object
 8   auto_year                  97306 non-null  float64
 9   auto_model                 97306 non-null  object
 10  color                      97306 non-null  object
 11  gear_type                  97306 non-null  object
 12  car_price                  97306 non-null  float64
 13  gender_cd_M-1_F-0          97307 non-null  int64
 14  age                        97306 non-null  float64
 15  marital_status_cd          75352 non-null  object
 16  children_cnt               97306 non-null  float64
 17  education_level_cd         68006 non-null  object
 18  person_monthly_income_amt  97306 non-null  float64
 19  day_of_week                97306 non-null  object
 20  public_holiday_1-f_0-t     97307 non-null  int64
 21  offencedatetime            97306 non-null  object
dtypes: float64(8), int64(3), object(11)
memory usage: 16.3+ MB

In [15]:
data['offencedatetime'] = pd.to_datetime(data['offencedatetime'])

In [19]:
data.drop(columns='Unnamed: 0', axis=1, inplace=True)

In [21]:
data.describe()

,party_rk,engine_type,engine_power,auto_year,car_price,gender_cd_M-1_F-0,age,children_cnt,person_monthly_income_amt,public_holiday_1-f_0-t,offencedatetime
count,9.730600e+04,97306.000000,97306.000000,97306.000000,97306.000000,97307.000000,97306.000000,97306.000000,9.730600e+04,97307.000000,97306
mean,5.449193e+08,2.156845,161.532329,2013.258463,1581.552391,0.687299,37.610127,0.139714,1.054343e+04,0.748980,2024-05-15 22:00:41.765831680
min,1.180000e+02,0.000000,0.000000,1910.000000,46.000000,0.000000,4.000000,0.000000,0.000000e+00,0.000000,2024-04-28 00:01:34
25%,2.724549e+08,1.600000,107.000000,2009.000000,659.000000,0.000000,30.000000,0.000000,8.000000e+01,0.000000,2024-05-08 15:49:59
50%,5.453083e+08,1.800000,145.000000,2013.000000,1105.000000,1.000000,37.000000,0.000000,1.400000e+02,1.000000,2024-05-16 18:32:26
75%,7.856307e+08,2.400000,190.000000,2018.000000,1945.000000,1.000000,44.000000,0.000000,3.000000e+02,1.000000,2024-05-23 08:05:02.750000128
max,1.228628e+09,999.000000,1770.000000,2024.000000,35470.000000,1.000000,88.000000,9.000000,8.691286e+08,1.000000,2024-05-27 23:59:59
std,3.076237e+08,8.494550,79.588675,6.135761,1622.693079,0.463596,10.597759,0.501737,2.786210e+06,0.433602,NaN

SARIMAX

In [22]:
from sktime.forecasting.model_selection import temporal_train_test_split
from sktime.forecasting.base import ForecastingHorizon

можно под y ебануть возраст водилы и возраст машины, бинарник с выходным или рабочим днем, колвом детей, бинарник с полом и месячной зп 
и сконектить связь с датой

In [41]:
y = data.age

In [26]:
from sktime.utils.plotting import plot_series

In [42]:
y = y.to_numpy(y)

In [43]:
y_train, y_test = temporal_train_test_split(y, test_size=48)
fn = ForecastingHorizon(y_test.index, is_relativ=False)

AttributeError: module 'dask' has no attribute 'dataframe'

In [44]:
y_train, y_test = temporal_train_test_split(y, test_size=48)
fn = ForecastingHorizon(y_test.index, is_relativ=False)

plot_series(y_train, y_test, labels=['y_train', 'y_test'])
print(y_train.shape[0], y_test.shape[0])

AttributeError: module 'dask' has no attribute 'dataframe'